runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js

- url: /.*
  script: service.main.app
  login: required


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
