runtime: python
env: flex

runtime_config:
  python_version: 3

handlers:
- url: /js
  static_dir: js

- url: /.*
  script: service.main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
